Try fix build gh pages 2

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -30,12 +30,17 @@ jobs:
           static_site_generator: next
 
       - name: Build and Export with Next.js 🏗️
-        run: |
-          npx next build
-          npx next export
+        run: npx next build
 
-      - name: List files
-        run: ls -al
+      - name: Verify export folder
+        run: |
+          if [ ! -d "./out" ]; then
+          echo "Error: Directory './out' does not exist! Export may have failed."
+          exit 1
+          fi
+
+          - name: List exported files
+            run: ls -al ./out
 
       - name: Upload artifact 📡
         uses: actions/upload-pages-artifact@v3
